# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/precise64"
config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/precise64"
  config.vm.box_check_update = false
  config.vm.hostname = "php53"  
  config.vm.network "public_network"
  config.vm.define "php53"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.network  "forwarded_port", guest: 80, host: 80
  config.vm.network  "forwarded_port", guest: 443, host: 443
  config.vm.synced_folder "/var/www/html", "/var/www" , :mount_options => ["dmode=777", "fmode=777"]  
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = 2
     vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
end
end
